// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ4tqBoqTfJz7AYhRtJ5k2EvkB5d0e-ZY',
    appId: '1:284479401585:web:26c7cab7a807dd3978f5d0',
    messagingSenderId: '284479401585',
    projectId: 'crud-app-ae4f1',
    authDomain: 'crud-app-ae4f1.firebaseapp.com',
    storageBucket: 'crud-app-ae4f1.appspot.com',
    measurementId: 'G-W145Z6BKTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTMcfuZSpvdZ9bj4JSBBr32GYkdWXpL8',
    appId: '1:284479401585:android:ea3c54178dafdea478f5d0',
    messagingSenderId: '284479401585',
    projectId: 'crud-app-ae4f1',
    storageBucket: 'crud-app-ae4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO4RCf5SkoxRCfJHKEt97Dzf18M41L1a0',
    appId: '1:284479401585:ios:f6e5c4082861028378f5d0',
    messagingSenderId: '284479401585',
    projectId: 'crud-app-ae4f1',
    storageBucket: 'crud-app-ae4f1.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO4RCf5SkoxRCfJHKEt97Dzf18M41L1a0',
    appId: '1:284479401585:ios:f6e5c4082861028378f5d0',
    messagingSenderId: '284479401585',
    projectId: 'crud-app-ae4f1',
    storageBucket: 'crud-app-ae4f1.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ4tqBoqTfJz7AYhRtJ5k2EvkB5d0e-ZY',
    appId: '1:284479401585:web:38745e05c519acfa78f5d0',
    messagingSenderId: '284479401585',
    projectId: 'crud-app-ae4f1',
    authDomain: 'crud-app-ae4f1.firebaseapp.com',
    storageBucket: 'crud-app-ae4f1.appspot.com',
    measurementId: 'G-SR2Y787FGN',
  );

}